### ISSUE TITLE
TODO tasks

### ISSUE THREAD

**Issue by acrobat** [rvanginneken/ssx#2]
Current features (backport from secret santa):

- [ ] ...

New features (more like ideas to implement):

- [ ] Make it possible to create account (using facebook, google+, ...)
- [ ] Add specific link to wishlist item (ex. link to specific site to directly order it)
- [ ] Possibility to send mail to match when they did not yet created a wishlist (anonymous mail)
- [ ] Send mail to match when the wishlist is created/updated (but limit amount of mails)
- [ ] CSV import of party users

I will finish the list of current features in the next few days!
